IT1566/Assignment1/src/models.py
from flask_login import UserMixin
from . import db


class User(UserMixin, db.Model):
    """
    Schema reference:

    CREATE TABLE "accounts" (
        "id"	INTEGER NOT NULL,
        "username"	BLOB NOT NULL UNIQUE,
        "password"	BLOB NOT NULL,
        "points"	INTEGER NOT NULL,
        "priv_lvl"	INTEGER NOT NULL,
        "email"	TEXT NOT NULL,
        PRIMARY KEY("id" AUTOINCREMENT)
    );
    """
    __tablename__ = "accounts"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    points = db.Column(db.Integer, nullable=False)
    priv_lvl = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return f"<User {self.id}:{self.username}>"


class Transaction(db.Model):
    """
    Schema reference:

    CREATE TABLE "transactions" (
        "txn_id"	TEXT NOT NULL UNIQUE,
        "txn_date"	NUMERIC NOT NULL,
        "txn_type"	INTEGER NOT NULL,
        "amt"	INTEGER NOT NULL,
        "src_usr_id"	INTEGER NOT NULL,
        "dest_usr_id"	INTEGER NOT NULL,
        "data"	BLOB,
        PRIMARY KEY("txn_id"),
        FOREIGN KEY("src_usr_id") REFERENCES "accounts"("id")
    );
    """
    __tablename__ = "transactions"
    txn_id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    txn_date = db.Column(db.DateTime, nullable=False)
    txn_type = db.Column(db.Integer, nullable=False)
    amt = db.Column(db.Integer, nullable=False)
    src_usr_id = db.Column(db.Integer, db.ForeignKey(
        "accounts.id"), nullable=False)
    dest_usr_id = db.Column(db.Integer, db.ForeignKey(
        "accounts.id"), nullable=False)
    data = db.Column(db.String(300), nullable=True)

    def __repr__(self):
        return f"<Transaction {self.id}>"

    def get_transactions_by_user(self, user_id: int) -> dict[list]:
        """
        Get all transactions for a user by user ID
        
        Args:
            user_id (int): User ID
        
        Returns:
            dict[list]: Dictionary containing lists of transactions
        """
        return {
            "from": Transaction.query.filter_by(src_usr_id=user_id).all(),
            "to": Transaction.query.filter_by(dest_usr_id=user_id).all()
        }


class CollectionPoint(db.Model):
    """
    Schema reference:

    CREATE TABLE "collection_points" (
        "id"	INTEGER NOT NULL,
        "loc_name"	TEXT NOT NULL UNIQUE,
        "capacity" INTEGER NOT NULL DEFAULT 0,
        "storage_lvl"	NUMERIC NOT NULL DEFAULT 0,
        PRIMARY KEY("id" AUTOINCREMENT)
    );  
    """
    __tablename__ = "collection_points"
    id = db.Column(db.Integer, primary_key=True)
    loc_name = db.Column(db.String(100), unique=True, nullable=False)
    capacity = db.Column(db.Integer, nullable=False)
    storage_lvl = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return f"<CollectionPoint {self.id}:{self.loc_name}>"
    
    def get_collection_points(self, storage_lvl: int) -> list:
        """
        Get all collection points with storage level greater than or equal to the specified level
        
        Args:
            storage_lvl (int): Storage level
        
        Returns:
            list: List of collection points
        """
        return CollectionPoint.query.filter(CollectionPoint.storage_lvl >= storage_lvl).all()

class RewardItem(db.Model):
    """
    Schema reference:
    """
    __tablename__ = "rewards"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    cost = db.Column(db.Integer, nullable=False)
    stock = db.Column(db.Integer, nullable=False)
    description = db.Column(db.String(100), nullable=False)
    
    def __repr__(self):
        return f"<RewardItem {self.id}:{self.name}>"

IT1566/Assignment1/app.py
from src import create_app

app = create_app()

if __name__ == "__main__":
    app.run(debug=True)

IT1566/Assignment1/main.py
from src import create_app

app = create_app()

if __name__ == "__main__":
    app.run(debug=True)

IT1566/Assignment1/src/__init__.py
from flask import Flask
from flask_login import *
from flask_sqlalchemy import SQLAlchemy
from dotenv import load_dotenv
import os

db = SQLAlchemy()

def create_app():
    app = Flask(__name__, template_folder="../templates")
    
    load_dotenv()
    app.config["SECRET_KEY"] = os.getenv("FLASK_SECRET_KEY")
    app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv("DB_PRIMARY_URI")
    db.init_app(app)
    
    from . import models
    
    with app.app_context():
        db.create_all()
    
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = "auth.login"
    
    from .models import User
    @login_manager.user_loader
    def load_user(user_id: int):
        return User.query.get(int(user_id))
    
    from src.auth import auth as auth_blueprint
    from src.routes import routes as routes_blueprint
    from src.api import api as api_blueprint
    
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(api_blueprint)
    app.register_blueprint(routes_blueprint)
    
    return app

IT1566/Assignment1/src/auth.py
from flask import *
from flask_login import *
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from .models import User

auth = Blueprint("auth", __name__)

@auth.route("/login")
def login():
    return render_template("login.html")

@auth.route("/login", methods=["POST"])
def login_post():
    email = request.form.get("email")
    password = request.form.get("password")
    remember = True if request.form.get("remember") else False
    
    user = User.query.filter_by(email=email).first()
    if not user or not check_password_hash(user.password, password):
        flash("Please check your login details and try again.")
        return redirect(url_for("auth.login"))
    login_user(user, remember=remember)
    return redirect(url_for("routes.index"))

@auth.route("/register")
def register():
    return render_template("register.html")

@auth.post("/register")
def register_post():
    email = request.form.get("email")
    username = request.form.get("username")
    password = request.form.get("password")
    
    user = User.query.filter_by(email=email).first()
    if user:
        flash("Username or email already exists.")
        return redirect(url_for("auth.register"))
    
    new_user = User(email=email, username=username, password=generate_password_hash(password, method="scrypt"), points=0, priv_lvl=0)
    db.session.add(new_user)
    db.session.commit()
    return redirect(url_for("auth.login"))

@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

IT1566/Assignment1/src/routes.py
from flask import *
from flask_login import login_required
from . import db

routes = Blueprint("routes", __name__)

@routes.route("/")
@login_required
def index():
    return render_template("index.html")

@routes.route("/account")
@login_required
def account():
    return render_template("account.html")

IT1566/Assignment1/templates/account.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, Anthony!
</h1>
{% endblock %}

IT1566/Assignment1/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('routes.index') }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for('routes.account') }}" class="navbar-item">
                                Profile
                            </a>
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.register') }}" class="navbar-item">
                                Sign Up
                            </a>
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

IT1566/Assignment1/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}

IT1566/Assignment1/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox" name="remember">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

IT1566/Assignment1/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/register">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="Username" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}